title: Data Culture Group @ Northeastern University
description: Interrogating our datafied society
author: Rahul Bhargava
google_analytics: G-4JGZ8C6CST

enableTags: true
tagarray: []

permalink: /:year/:month/:day/:title:output_ext

collections:
  authors:
    output: true
  projects:
    output: true
    permalink: /projects/:path/

social:
    - logo: "mastodon-logo.png"
      link: "https://vis.social/@rahulbot"
      name: "Mastodon"
    - logo: "linkedin-logo.png"
      link: "https://www.linkedin.com/in/rahulbot/"
      name: "LinkedIn"
    - logo: "twitter-logo.png"
      link: "https://twitter.com/rahulbot"
      name: "Twitter"
    - logo: "instagram-logo.png"
      link: "https://www.instagram.com/rahulbot/"
      name: "Instagram"

share:
  twitter_username: rahulbot

urls:
    - text: Projects
      url: projects/
    - text: About
      url: about/
    - text: Newsletter
      url: http://eepurl.com/iyGMNs
    - text: Code
      url: https://github.com/orgs/dataculturegroup/

url: "https://dataculturegroup.org"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap

kramdown:
  syntax_highlighter: rouge

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      permalink: /projects/:title:output_ext
  - scope:
      path: ""
    values:
      layout: "default"

whitelist:
  - jekyll-redirect-from
